version: '3.8'

services:
  nest_service:
    build: ./nest_service
    command: npm run start:dev
    ports:
      - "3000:3000"
    env_file:
      - ./nest_service/.env
    depends_on:
      - db

  dotnet_service:
    build:
      context: ./dotnet_service
      target: build
    command: dotnet watch run --urls "http://*:8080"
    ports:
      - "5000:8080"
    volumes:
      - ./dotnet_service:/src
    env_file:
      - ./dotnet_service/.env
    depends_on:
      - db
      - redis

  django_service:
    build: ./django_service
    ports:
      - "8000:8000"
    volumes:
      - ./django_service:/usr/src/app
    env_file:
      - ./django_service/.env
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2521
      POSTGRES_DB: real-state
    ports:
      - "5420:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: 